require("melxaco.plugins-setup")
require("melxaco.core.options")
require("melxaco.core.keymaps")
require("melxaco.core.colorscheme")
require("melxaco.plugins.comment")
require("melxaco.plugins.nvim-tree")
require("melxaco.plugins.lualine")
require("melxaco.plugins.telescope")
