print("[D] Initialize lua setup (init.lua)")

--require("melxaco.plugins-setup")
require("melxaco.config.lazy")
require("melxaco.core.options")
require("melxaco.core.keymaps")
--require("melxaco.core.colorscheme")
--require("melxaco.plugins.comment")
--require("melxaco.plugins.nvim-tree")
-- require("melxaco.plugins.lualine")
-- require("melxaco.plugins.telescope")
-- require("melxaco.plugins.nvim-cmp")
-- require("melxaco.plugins.lsp.mason")
-- require("melxaco.plugins.lsp.lspsaga")
-- require("melxaco.plugins.lsp.lspconfig")
-- require("melxaco.plugins.autopairs")
-- require("melxaco.plugins.treesitter")
-- require("melxaco.plugins.gitsigns")
-- require("melxaco.plugins.lsp.null-ls")
